name: opentelemetry_logging
description: A simple library implementing sending logs to OpenTelemetry, supports gRPC and HTTP protocols.
version: 0.4.0
repository: https://github.com/NicolaVerbeeck/opentelemetry_logging_dart
topics:
  - logging
  - opentelemetry

environment:
  sdk: ^3.6.0

dependencies:
  fixnum: ^1.1.1
  grpc: ^5.0.0
  http: ^1.4.0
  protobuf: ^5.0.0

dev_dependencies:
  lint: ^2.8.0
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.24.0

